Add easy autopkgtest dependency installation, misc run_autopkgtest improvements

diff --git a/run_autopkgtest b/run_autopkgtest
--- a/run_autopkgtest
+++ b/run_autopkgtest
@@ -8,9 +8,9 @@ set -o nounset
 set -o errtrace
 set -o pipefail
 
-autopkgtest_tarball_path="$HOME/.cache/sbuild/bookworm-amd64.tar.zst"
 privleap_project_dir="$(dirname "$(readlink -f "${0}")")"
 target_distribution="bookworm"
+autopkgtest_tarball_path="${HOME}/.cache/sbuild/${target_distribution}-amd64.tar.zst"
 
 create_autopkgtest_tarball() {
   mkdir -p ~/.cache/sbuild
@@ -19,7 +19,7 @@ create_autopkgtest_tarball() {
     --skip=output/dev \
     --variant=buildd \
     "${target_distribution}" \
-    "${HOME}/.cache/sbuild/${target_distribution}-amd64.tar.zst" \
+    "${autopkgtest_tarball_path}" \
     --customize-hook='chroot "$1" passwd --delete root' \
     --customize-hook='chroot "$1" useradd --home-dir /home/user --create-home user' \
     --customize-hook='chroot "$1" passwd --delete user' \
@@ -28,11 +28,36 @@ create_autopkgtest_tarball() {
     https://deb.debian.org/debian
 }
 
-run_autopkgtest() {
-  ## Ensure unshare executable exists, it's critical for this script to work
-  if ! [ -x '/usr/bin/unshare' ]; then
-    1>&2 echo 'Cannot find unshare executable!'
+offer_package_install() {
+  local pkg_name install_yn
+  pkg_name="$1"
+  1>&2 echo "${pkg_name} is not installed, but is needed to run the test suite."
+  1>&2 echo -n 'Would you like to install it now? [y/N] '
+  read -r install_yn
+  if [ "${install_yn,,}" = 'y' ]; then
+    sudo apt-get install "${pkg_name}"
+  else
+    1>&2 echo 'Test run aborted.'
     exit 1
+  fi
+}
+
+run_autopkgtest() {
+  local reset_autopkgtest_tarball
+  reset_autopkgtest_tarball="${1:-}"
+  ## Dependency checks
+  if ! [ -x '/usr/bin/unshare' ]; then
+    1>&2 echo 'unshare is not executable or does not exist!'
+    exit 1
+  fi
+  if ! [ -f '/usr/bin/autopkgtest' ]; then
+    offer_package_install 'autopkgtest'
+  fi
+  if ! [ -f '/usr/bin/mmdebstrap' ]; then
+    offer_package_install 'mmdebstrap'
+  fi
+  if ! [ -f '/usr/bin/dh' ]; then
+    offer_package_install 'debhelper'
   fi
   if [ "$(basename "${privleap_project_dir}")" != 'privleap' ]; then
     1>&2 echo 'The run_autopkgtest script does not appear to be in the root of the privleap source tree!'
@@ -53,6 +78,9 @@ run_autopkgtest() {
     }
   fi
 
+  if [ "${reset_autopkgtest_tarball}" = '--reset-tarball' ]; then
+    rm -f "${autopkgtest_tarball_path}"
+  fi
   if ! [ -f "${autopkgtest_tarball_path}" ]; then
     create_autopkgtest_tarball
   fi
@@ -67,4 +95,4 @@ run_autopkgtest() {
   echo "Test complete. Results are stored in ${privleap_project_dir}/privleap-test-log.txt."
 }
 
-run_autopkgtest
+run_autopkgtest "$@"
